 1742  curl v2ex.com | sed '/(\d+?).*人在线/p\1'
 1743  curl v2ex.com | sed '/(\d+?).*人在线/d'
 1744  curl v2ex.com | sed '/(\d+?).*人在线/d!'
 1745  curl v2ex.com | sed '/(\d+?).*人在线/D'
 1746  curl v2ex.com | sed '/(\d+?).*人在线/!d'
 1747  curl v2ex.com | sed '/([[:digits:]]+?).*人在线/!d'
 1748  man sed
 1749  curl v2ex.com | sed 'd/([[:digits:]]+?).*人在线/'
 1750  curl v2ex.com | sed 'd/(\d+?).*人在线/'
 1751  curl v2ex.com | sed '/(\d+?).*人在线/'
 1752  curl v2ex.com | sed '/(\d+?).*人在线/d'
 1753  curl v2ex.com | sed '/(\d+?).*人在线/!d'
 1754  curl v2ex.com | sed '/lang/!d'
 1755  curl v2ex.com | sed '/lang/!d' | grep lang
 1756  curl v2ex.com | sed '/(\d\{-1,\})\.*人在线/!d'
 1757  curl v2ex.com | sed '/\(\d\{-1,\}\)\.*人在线/!d'
 1758  curl v2ex.com | sed '/\(\d\{1,\}\)\.*人在线/!d'
 1759  curl v2ex.com | sed '/\(\d\{1,\}\).*人在线/!d'
 1760  curl v2ex.com | sed '/\(\d\{1,\}\).*人在线/!ds//\1/'
 1761  curl v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p'
 1762  curl v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/s//\1/'
 1763  curl v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/s/^.*$/\1/'
 1764  curl v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/s/^.*\(\d\{1,\}\).*人在线.*$/\1/'
 1765  man curl
 1766  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/s/^.*\(\d\{1,\}\).*人在线.*$/\1/'
 1767  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/s/^.*\(\d\{1,\}.*人在线\).*$/\1/'
 1768  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/s/^.*\(\d\{1,\}.*人在线\).*$/\0/'
 1769  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/s/^.*\(\d\{1,\}.*人在线\).*$/------/'
 1770  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/s/lang/---------/'
 1771  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/s/png/---------/'
 1772  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p'
 1773  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/{s/^.*$/\1/}'
 1774  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/{s/^.*\(\d\{1,\}\).*人在线.*$/\1/}'
 1775  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/{s/FAQ/bbbbbbbbbbbbbbbbbbbb/}'
 1776  man sed
 1777  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/' | sed 's/FAQ/bbbbbbbbbbbbbbbbbbbb/'
 1778  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/FAQ/bbbbbbbbbbbbbbbbbbbb/'
 1779  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/\(\d\{1,\}\).*人在线/\1/'
 1780  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*\(\d\{1,\}\).*人在线.*/\1/'
 1781  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*\([:digit:]\{1,\}\).*人在线.*/\1/'
 1782  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*\([[digit:]]\{1,\}\).*人在线.*/\1/'
 1783  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*\([[digit:]]\{1,\}\).*人在线.*$/\1/'
 1784  echo 'sssssssss dddddd' | sed 's/^.*$/xxxx/'
 1785  echo 'sssssssss dddddd' | sed 's/^.*\(sss\).*$/\1/'
 1786  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*\([[:digit:]]\{1,\}\).*人在线.*$/\1/'
 1787  curl -s v2ex.com
 1788  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p'
 1789  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*\([[:digit:]]\{1,\}\).*人在线.*$/\1/'
 1790  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*?\([[:digit:]]\{1,\}\).*人在线.*$/\1/'
 1791  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^[^\d]*\([[:digit:]]\{1,\}\).*人在线.*$/\1/'
 1792  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^[^[:digit:]]*\([[:digit:]]\{1,\}\).*人在线.*$/\1/'
 1793  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^[^[:digit:]]*\([[:digit:]]\{1,\}\)[^[:digit:]]*人在线.*$/\1/'
 1794  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^[^[:digit:]]*\([[:digit:]]+\)[^[:digit:]]*人在线.*$/\1/'
 1795  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^[^[:digit:]]*\([[:digit:]]*\)[^[:digit:]]*人在线.*$/\1/'
 1796  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*\([[:digit:]]*\).*人在线.*$/\1/'
 1797  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*\([[:digit:]]\{3\}\).*人在线.*$/\1/'
 1798  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*\([[:digit:]]*\)\s*.*人在线.*$/\1/'
 1799  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*\(\d\{3\}\)\s*.*人在线.*$/\1/'
 1800  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*\([[:digit:]]\{3\}\)\s*.*人在线.*$/\1/'
 1801  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*[^[:digit:]]\{3\}\([[:digit:]]*\)[^[:digit:]]*人在线.*$/\1/'
 1802  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*[^[:digit:]]\{1\}\([[:digit:]]*\)[^[:digit:]]*人在线.*$/\1/'
 1803  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*[^[:digit:]]\{2\}\([[:digit:]]*\)[^[:digit:]]*人在线.*$/\1/'
 1804  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*[^0-9]\{1\}\([[:digit:]]*\)[^[:digit:]]*人在线.*$/\1/'
 1805  curl -s v2ex.com | sed -n '/\(\d\{1,\}\).*人在线/p' | sed 's/^.*[^0-9]\{2\}\([[:digit:]]*\)[^[:digit:]]*人在线.*$/\1/'
 1830  curl -s v2ex.com | sed -n '/人在线/p' | sed -r 's/^.*\s+([[:digit:]]+)\s*人在线.*$/\1/'
